---
title: Figure S1 Strain responses by toxicant
---

```{r}
library(dplyr)
library(ggplot2)
library(ggh4x)
library(ggrepel)

source("bin/tox_colors.R")
source("bin/outs.R")
source("bin/materials_key.R")

#### Inputs ####

# load H2 and h2 rdata files
load("data/processed/heritability/h2.list.mean.rda")

# load the H2 data from boots
load("data/processed/heritability/H2.parametric.boot.list.10000.rda")

# load the tox data
tox <- data.table::fread("data/processed/tox_data/con_metadata.csv") %>%
  dplyr::filter(type == "Toxicant")

#### Create dataframes for plotting ####

## H2 ##

# setup as data frame
H2.df.list <- NULL
for (i in 1:length(H2.list)) {
  drug <- names(H2.list)[i]
  o <- H2.list[[i]][[1]] %>%
    dplyr::mutate(drug = drug)

  H2.df.list[[i]] <- o
}
# bind list
H2.df <- data.table::rbindlist(H2.df.list) %>%
  dplyr::filter(drug %in% unique(tox$drug))

## h2 ##

h2.df.list.b <- NULL
for (i in 1:length(h2.list.mean)) {
  drug <- names(h2.list.mean)[i]
  o <- h2.list.mean[[i]] %>%
    dplyr::mutate(drug = drug)

  h2.df.list.b[[i]] <- o
}
# bind list
h2.df.b <- data.table::rbindlist(h2.df.list.b)


# ==============================================================================#
# Part 3: Plot H2 by h2 with means only for h2
# ==============================================================================#
# shape data to join
# join the H2 and h2 data
# h.b <- dplyr::left_join(H2.df, h2.df.b) %>%
#   dplyr::left_join(tox) %>%
#   dplyr::filter(big_class != "Flame Retardant") %>%
#   dplyr::mutate(nice_drug_label2 = stringr::str_replace(nice_drug_label2, pattern = "uM", replacement = "µM"))

# # make nice colors for class
# # class colors for y
# man_pal <- h.b %>%
#   dplyr::distinct(big_class) %>%
#   dplyr::arrange(big_class) %>%
#   dplyr::left_join(class.pal.df) %>%
#   dplyr::pull(col)

# # set strip col for y
# strip <- ggh4x::strip_themed(background_x = ggh4x::elem_list_rect(fill = man_pal))
# labels <- c("Fungicide" = "Fungicides",
#           "Herbicide" = "Herbicides",
#           "Insecticide" = "Insecticides",
#           "Metal" = "Metals")
# # plot it
# p.b <- ggplot2::ggplot(h.b) +
#     ggplot2::aes(x = H2.point, y = h2.point) +
#     ggplot2::geom_point() +
#     ggplot2::geom_pointrange(aes(ymin = h2.lower, ymax = h2.upper), size = 0.5, alpha = 0.2) +
#     ggplot2::geom_pointrange(aes(xmin = H2.CI.lower, xmax = H2.CI.upper), size = 0.5, alpha = 0.2) +
#     ggrepel::geom_text_repel(
#         aes(label = nice_drug_label2)
#         ) +
#     ggplot2::theme_bw() +
#     ggplot2::geom_abline(
#         color = "grey",
#         alpha = 0.5,
#         slope = 1,
#         intercept = 0,
#         linetype = 2
#         ) +
#     ggh4x::facet_wrap2(~big_class, strip = strip, labeller = as_labeller(labels)) +
#     ggplot2::labs(
#         x = expression(bold('Broad-sense heritability') ~ bolditalic(H)^{2}),
#         y = expression(bold('Narrow-sense heritability') ~ bolditalic(h)^{2})
#         ) +
#     ggplot2::theme(legend.position = "none",
#         panel.grid = element_blank(),
#         strip.text.y = element_text(
#                 size = 10,
#                 family = "Arial",
#                 face = "bold"
#                 ),
#         strip.text.x = element_text(
#                 size = 10,
#                 family = "Arial",
#                 face = "bold"
#                 ),
#         axis.text = element_text(
#                 size = 10,
#                 family = "Arial"
#                 ),
#         axis.title = element_text(
#                 size = 10
#                 )
#         ) +
#     ggplot2::scale_x_continuous(limits = c(0, 1), breaks = seq(0, 1, 0.2)) +
#     ggplot2::scale_y_continuous(limits = c(0, 1), breaks = seq(0, 1, 0.2))
# p.b


# Save the plot to manuscript folder
# ggplot2::ggsave(
#     filename = "figures/Figure_1/Figure_1.eps",
#     plot = p.b,
#     width = 7.5,
#     height = 4.5,
#     dpi = 300,
#     units = "in"
# )

# ggplot2::ggsave(
#     filename = "figures/Figure_1/Figure_1.png",
#     plot = p.b,
#     width = 7.5,
#     height = 4.5,
#     dpi = 300,
#     units = "in"
# )

# ==============================================================================#
# Figure S3: Plot H2 by h2 INCLUDE FLAME RETARDANTS
# ==============================================================================#

# shape data to join
# join the H2 and h2 data
h.b2 <- dplyr::left_join(H2.df, h2.df.b) %>%
  dplyr::left_join(tox) %>%
  # dplyr::filter(big_class != "Flame Retardant") %>%
  dplyr::mutate(nice_drug_label2 = stringr::str_replace(nice_drug_label2, pattern = "uM", replacement = "µM"))


# make nice colors for class
# class colors for y
man_pal2 <- h.b2 %>%
  dplyr::distinct(big_class) %>%
  dplyr::arrange(big_class) %>%
  dplyr::left_join(class.pal.df) %>%
  dplyr::pull(col)

# set strip col for y
strip2 <- ggh4x::strip_themed(background_x = ggh4x::elem_list_rect(fill = man_pal2))
labels2 <- c(
  "Flame Retardant" = "Flame Retardants",
  "Fungicide" = "Fungicides",
  "Herbicide" = "Herbicides",
  "Insecticide" = "Insecticides",
  "Metal" = "Metals"
)
# plot it
heritability_all_classes_p <- ggplot(h.b2, aes(x = H2.point, y = h2.point)) +
  geom_point() +
  geom_pointrange(aes(ymin = h2.lower, ymax = h2.upper), size = 0.5, alpha = 0.2) +
  geom_pointrange(aes(xmin = H2.CI.lower, xmax = H2.CI.upper), size = 0.5, alpha = 0.2) +
  ggrepel::geom_text_repel(aes(label = nice_drug_label2), size = 2.25) +
  theme_bw() +
  geom_abline(
    color = "grey",
    alpha = 0.5,
    slope = 1,
    intercept = 0,
    linetype = 2
  ) +
  ggh4x::facet_wrap2(~big_class, strip = strip2, labeller = as_labeller(labels2)) +
  ggplot2::labs(
    x = expression(bold("Broad-sense heritability") ~ bolditalic(H)^{
      2
    }),
    y = expression(bold("Narrow-sense heritability") ~ bolditalic(h)^{
      2
    })
  ) +
  ggplot2::theme(
    legend.position = "none",
    panel.grid = element_blank(),
    strip.text.y = element_text(
      size = 10,
      family = "Arial",
      face = "bold"
    ),
    strip.text.x = element_text(
      size = 10,
      family = "Arial",
      face = "bold"
    ),
    axis.text = element_text(
      size = 10,
      family = "Arial"
    ),
    axis.title = element_text(
      size = 10
    )
  ) +
  ggplot2::scale_x_continuous(limits = c(0, 1), breaks = seq(0, 1, 0.2)) +
  ggplot2::scale_y_continuous(limits = c(0, 1), breaks = seq(0, 1, 0.2))

# save the manuscript version
save_plot(
  heritability_all_classes_p,
  figure_fns$heritability_all_classes,
  w_in = 7.5,
  h_in = 5
)

```

```{r}
heritability_all_classes_p
```