---
title: "Table S1: Strain Information"
format: html
---

```{r}
#| include: false
library(tidyverse)
library(dplyr)
library(data.table)

# Source the portable project setup function
script_dir <- tryCatch(
  dirname(normalizePath(knitr::current_input())),
  error = function(e) getwd()
)

setup_file <- file.path(script_dir, "..", "bin", "setup_project_here.R")

if (file.exists(setup_file)) {
  source(setup_file)
  project_root <- setup_toxin_project_here()
} else {
  setup_file <- file.path(getwd(), "projects", "ToxinGWAS_Manuscript", "bin", "setup_project_here.R")
  if (file.exists(setup_file)) {
    source(setup_file)
    project_root <- setup_toxin_project_here()
  } else {
    stop("Could not find setup_project_here.R")
  }
}

if (is.null(project_root)) {
  stop("Could not locate ToxinGWAS_Manuscript project root.")
}


# source the helper functions
source(file.path(project_root, "bin", "general.R"))

source(file.path(project_root, "bin", "outs.R"))
source(file.path(project_root, "bin", "materials_key.R"))

# get the list of strains in the GWAS
load(file.path(project_root, "data", "raw", "phenotypes", "pheno.df.rda"))

# Read the strain means data
strains <- unique(pheno.df$strain)

# downlaod latest data from CeaNDR
ce_iso_loc <- data.table::fread("https://caendr.org/request-strains/download/c-elegans/20220216/strain-data/csv")

# Three strains have non-CaeNDR strain names in data,  c("CB4855" "CB4857" "PB306")
# these are c("ECA248" = "CB4855, ECA250 = "CB4857", "ECA259" = "PB306")
strains[!strains %in% ce_iso_loc$strain]
fix <- c("ECA248" = "CB4855", "ECA250" = "CB4857", "ECA259" = "PB306")

# make the table
tableS1 <- ce_iso_loc %>%
  dplyr::filter(strain %in% names(fix) | strain %in% strains) %>%
  dplyr::select(-1:-3, strain = isotype, caendr_release = release, -strain_set:-sequenced)

# # save the table
# rio::export(tableS1, file = "tables/tableS1.csv")

save_supp_table_csv(tableS1, "strain_table")
```

```{r}
#| label: tbl-strain-info
#| echo: false

tableS1
```
