---
title: "Supplementary Figure 5: All Toxins Interval Plot"
---

```{r}
#| label: all-tox-interval-setup

#| label: plot-interval-overlaps-setup
library(tidyverse)
library(data.table)

set.seed(123)

# source functions
source("bin/outs.R")
source("bin/materials_key.R")

```

# Overview
Code to plot the intervals detected by Inbred GWA for all 26 conditions, including conditions where no significant intervals were detected.

# Inputs
```{r}
#| label: all-tox-interval-inputs

# Path to neamscan output directory
ns_dir <- "data/processed/20231116_Analysis_NemaScan"

# toxicant condition metadata
tox_meta_fn <- "data/processed/tox_data/tox_metadata.csv"
chr_lens_fn <- "data/raw/c_elegans_chr_lengths.tsv"
```

# Main

## Load data
```{r}
chr_lens <- data.table::fread(chr_lens_fn) %>%
  dplyr::select(CHROM, startPOS = start, endPOS = stop)

tox_meta <- data.table::fread(tox_meta_fn) %>%
  dplyr::mutate(nice_drug_label2 = stringr::str_replace(nice_drug_label2, pattern = "uM", replacement = "µM"))


qtl_raw <- data.table::fread(
  glue::glue("{ns_dir}/INBRED/Mapping/Processed/QTL_peaks_inbred.tsv")
)
```

# Create dataframe for plotting
Join the QTL data with the toxicant metadata to get nice labels for plotting after formatting
```{r}
qtl_clean <- qtl_raw %>%
  # remove any CV_length traits
  dplyr::filter(!stringr::str_detect(trait, pattern = "CV_length")) %>%
  dplyr::rename(POS = peakPOS) %>%
  # Collapse to just distinct rows
  dplyr::distinct()

plot_data <- tox_meta %>%
  dplyr::select(trait, big_class, nice_drug_label2) %>%
  dplyr::left_join(., qtl_clean, by = "trait") %>%
  # Arrange to match the factor ordering you want
  dplyr::arrange(
    desc(big_class),
    desc(nice_drug_label2)
  ) %>%
  dplyr::mutate(
    nice_drug_label2 = factor(
      nice_drug_label2,
      levels = unique(nice_drug_label2)
    )
  ) %>%
  # adjust FR name so it is broken onto two lines in the plot
  dplyr::mutate(big_class = case_when(
    big_class == "Flame Retardant" ~ "Flame\nRetardant",
    TRUE ~ big_class
  ))

head(plot_data)
```

# Create accessory data frames for plot formatting
```{r}
# Create chr_lens2 with ALL toxicant levels
chr_lens2 <- chr_lens %>%
  tidyr::pivot_longer(cols = -CHROM, names_to = "poop", values_to = "POS") %>%
  dplyr::select(-poop) %>%
  # create a row for every combination to ensure y-axis levels are represented
  tidyr::crossing(
    .,
    plot_data %>%
      dplyr::distinct(nice_drug_label2, big_class, trait)
  )

class.pal.df <- tibble::tibble(
  col = c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#D55E00"),
  big_class = c("Control", "Flame\nRetardant", "Fungicide", "Herbicide", "Insecticide", "Metal")
)

# class colors for y
man_pal <- plot_data %>%
  dplyr::distinct(big_class) %>%
  dplyr::left_join(class.pal.df) %>%
  dplyr::pull(col)

strip_y <- ggh4x::strip_themed(background_y = ggh4x::elem_list_rect(fill = man_pal))
```

# Create plot
```{r}
# Create plot
all_tox_intervals_p <- ggplot() +
  theme_bw() +
  geom_point(
    data = plot_data %>% dplyr::filter(!is.na(POS)), # Filter NAs here
    mapping = aes(
      x = POS / 1000000,
      y = nice_drug_label2,
      fill = log10p
    ),
    size = 4,
    stroke = 0.5,
    shape = 24
  ) +
  ggplot2::geom_segment(
    data = plot_data %>% dplyr::filter(!is.na(startPOS)), # Filter NAs here
    mapping = ggplot2::aes(
      x = startPOS / 1e6,
      xend = endPOS / 1e6,
      y = nice_drug_label2,
      yend = nice_drug_label2
    ),
    colour = "black",
    linewidth = 1.5
  ) +
  geom_point(data = chr_lens2, mapping = aes(x = POS / 1000000, y = nice_drug_label2), alpha = 0.0) +
  ggh4x::facet_grid2(
    big_class ~ CHROM,
    scales = "free",
    space = "free",
    strip = strip_y
  ) +
  theme(
    strip.text.y.right = element_text(angle = 0, family = "Helvetica", size = 9, face = "bold", lineheight = 0.9),
    strip.text.x = element_text(family = "Helvetica", size = 10, face = "bold"),
    axis.text.y = element_text(family = "Helvetica", size = 10, face = "bold"),
    axis.title.y = element_blank(),
    axis.title.x = element_text(family = "Helvetica", size = 10, face = "bold"),
    axis.text = element_text(family = "Helvetica", size = 10),
    legend.text = element_text(family = "Helvetica", size = 10),
    legend.title = element_text(family = "Helvetica", size = 10, face = "bold"),
    legend.position = "bottom",
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(),
    panel.grid.minor.y = element_blank(),
    panel.grid.major.y = element_blank(),
    strip.background.x = ggplot2::element_rect(
      color = "black", fill = "white", linewidth = 0.5, linetype = "solid"
    ),
    plot.margin = unit(c(7.5, 7.5, 0, 7.5), "pt")
  ) +
  scale_fill_gradient(
    low = "lightblue", high = "darkred",
    name = expression(-log[10](italic(p)))
  ) +
  labs(
    x = "Genomic position (Mb)"
  )
```

```{r}
#| fig-width: 7
#| fig-height: 10
all_tox_intervals_p
```

```{r}
#| label: plot-interval-overlaps-output
save_plot(
  all_tox_intervals_p,
  sup_figure_fns$all_tox_intervals,
  w_in = 7.5,
  h_in = 10
)
```