---
title: "Table S7: Candidate Genes and GO terms"
format: html
---

Based on original candidate gene identification script from analysis repository `create_candidate_table.R`

```{r}
#| label: candidate-genes-table-setup
#| include: false

library(dplyr)
library(data.table)
library(flextable)

set.seed(123)

# source the helper functions
source("bin/general.R")
source("bin/outs.R")
source("bin/materials_key.R")
source("bin/candidate_groupGO.R")
```

Create a flexttable
```{r}
candidate_ft <- candidate_flex_table_pre %>%
  flextable::flextable(
    col_keys = c(
      "Gene",
      "Details",
      "Marker",
      "Beta Coefficient",
      "Effect Allele",
      "Other Allele",
      "Log10p",
      "LD(r2)",
      "MAF",
      "Interval",
      "Interval Rank"
    ),
  ) %>%
  # make the gene name bold and italic
  flextable::italic(j = 1, i = ~ !is.na(Gene), part = "body") %>%
  # center the rank column
  flextable::align(j = "Interval Rank", align = "center", part = "all") %>%
  # replace NA values with "N/a"
  flextable::compose(j = "Interval Rank", value = as_paragraph(ifelse(is.na(`Interval Rank`), "N/a", `Interval Rank`))) %>%
  flextable::set_table_properties(layout = "autofit") %>%
  flextable::line_spacing(space = 1, part = "all") %>%
  flextable::align(align = "left", part = "all") %>%
  flextable::set_table_properties(
    layout = "autofit",
    width = 1,
    opts_word = list(split = FALSE, keep_with_next = TRUE)
  ) %>%
  flextable::paginate(
    group = "Gene",
    group_def = c("rle")
  )

# fns <- table_fns[["candidate_ft"]]
# docx_fn <- fns$docx

# flextable::save_as_docx(candidate_ft, path = docx_fn)
```

```{r}
candidate_ft
```

Save the tabels with standard functions
```{r}
save_supp_table_csv(candidate_flex_table_pre, "candidate_genes")
save_supp_table_flextable(candidate_ft, "candidate_genes")
```